#!/bin/bash
#SBATCH -A uppmax2026-1-61
#SBATCH -p pelle
#SBATCH -n 4
#SBATCH -t 24:00:00
#SBATCH -J canu_local
#SBATCH -o /home/padi4950/uppmax/efaecium_E745/logs/canu.out
#SBATCH -e /home/padi4950/uppmax/efaecium_E745/logs/canu.err

module load SAMtools/1.22.1-GCC-13.3.0
module load canu/2.3-GCCcore-13.3.0-Java-17

cd /home/padi4950/uppmax/efaecium_E745

canu \
  -p efaecium \
  -d results/canu/pacbio \
  genomeSize=3m \
  useGrid=false \
  maxThreads=2 \
  maxMemory=10 \
  corThreads=2 \
  ovlThreads=2 \
  batThreads=2 \
  -pacbio data/raw_data/DNA_PacBio/*.fastq.gz
