#!/bin/bash
#SBATCH -A uppmax2026-1-61
#SBATCH -p pelle
#SBATCH -n 2
#SBATCH -t 24:00:00
#SBATCH -J eggnog
#SBATCH -o /home/padi4950/uppmax/efaecium_E745/logs/eggnog.out
#SBATCH -e /home/padi4950/uppmax/efaecium_E745/logs/eggnog.err

module load eggnog-mapper/2.1.13-gfbf-2024a

emapper.py \
-i /home/padi4950/uppmax/efaecium_E745/results/prokka/efaecium.faa \
-o efaecium_eggnog \
--data_dir /home/padi4950/uppmax/efaecium_E745/resources/eggnog-mapper/bianca \
--output_dir /home/padi4950/uppmax/efaecium_E745/results/eggnog \
--cpu 2 \
--override
